apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: argocd
  finalizers:
  # Finalizer ensures that project is not deleted until it is not referenced by any application
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster addons
  sourceRepos:
  - "https://github.com/bcrisp4/kubernetes-config.git"
  destinations:
  - namespace: "*"
    name: "do-nyc3-prod-1"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
