apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: https://argocd.bc4.uk
  service.github: |
    appID: 378490
    installationID: 40919749
    privateKey: $github-privateKey
  trigger.app-sync: |
    - when: app.status.operationState.phase in ['Running']
      description: Application is being synced
      send: [app-sync-running]
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      description: Application is synced and healthy. Triggered once per commit.
      send: [app-sync-succeeded]
    - when: app.status.operationState.phase in ['Error', 'Failed']
      description: Application syncing has failed
      send: [app-sync-failed]
    - when: app.status.health.status == 'Degraded'
      description: Application has degraded
      send: [app-health-degraded]
    - when: app.status.sync.status == 'Unknown'
      description: Application status is 'Unknown'
      send: [app-sync-status-unknown]
  template.app-sync-running: |
    message: |
      Sync in progress
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.syncResult.revision}}"
      status:
        state: pending
        label: "{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
      deployment:
        state: pending
        environmentURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        logURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        requiredContexts: []
  template.app-sync-succeeded: |
    message: |
      Sync succeeded
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.syncResult.revision}}"
      status:
        state: success
        label: "{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
      deployment:
        state: success
        environmentURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        logURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        requiredContexts: []
  template.app-sync-failed: |
    message: |
      Sync failed
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.syncResult.revision}}"
      status:
        state: failure
        label: "{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
      deployment:
        state: failure
        environmentURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        logURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        requiredContexts: []
  template.app-health-degraded: |
    message: |
      Health degraded
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.syncResult.revision}}"
      status:
        state: error
        label: "{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
      deployment:
        state: error
        environmentURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        logURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        requiredContexts: []
  template.app-sync-status-unknown: |
    message: |
      Sync status unknown
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.syncResult.revision}}"
      status:
        state: error
        label: "{{.app.metadata.name}}"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
      deployment:
        state: error
        environmentURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        logURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        requiredContexts: []
