apiVersion: v1
data:
  accounts.ben: apiKey,login
  accounts.ben.enabled: "true"
  admin.enabled: "false"
  applicationsetcontroller.enable.new.git.file.globbing: "true"
  resource.customizations.ignoreDifferences.apps_StatefulSet: |
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'
  resource.customizations.ignoreDifferences.monitoring.coreos.com_ServiceMonitor: |
    jqPathExpressions:
      - '.spec.endpoints[]?.relabelings[]?.action'
  resource.exclusions: |
    - apiGroups:
        - "apps/*"
      kinds:
        - "ControllerRevision"
      clusters:
        - "*"
    - apiGroups:
        - "discovery.k8s.io/*"
      kinds:
        - "EndpointSlice"
      clusters:
        - "*"
    - apiGroups:
        - "cilium.io/*"
      kinds:
        - "CiliumEndpoint"
        - "CiliumIdentity"
      clusters:
        - "*"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
