apiVersion: v1
data:
  accounts.ben: apiKey,login
  accounts.ben.enabled: "true"
  admin.enabled: "false"
  applicationsetcontroller.enable.new.git.file.globbing: "true"
  resource.exclusions: |
    - apiGroups:
        - "*"
      kinds:
        - "CiliumEndpoint"
      clusters:
        - "*"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
