apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.github: |
    appID: 378490
    installationID: 40919749
    privateKey: $github-privateKey
  trigger.app-sync: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      description: Application is synced and healthy. Triggered once per commit.
      send: [app-sync-succeeded]
  template.app-sync-succeeded: |
    message: |
      {{.app.metadata.name}} sync succeeded.
    github:
      repoURLPath: "{{.app.spec.source.repoURL}}"
      revisionPath: "{{.app.status.operationState.syncResult.revision}}"
      status:
        state: success
        label: "cd/{{.app.metadata.name}}"
        targetURL: "https://{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
      deployment:
        state: success
        environmentURL: "https://{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        logURL: "https://{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        requiredContexts: []
