apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/bcrisp4/kubernetes-infrastructure.git
              revision: HEAD
              directories:
                - path: "core/*"
                - path: "monitoring/*"
          - clusters:
              selector:
                matchLabels:
                  kubernetes.bc4.uk/environment: "production"
              values:
                environment: production

  template:
    metadata:
      name: "{{ path.basenameNormalized }}-{{ nameNormalized }}"
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/bcrisp4/kubernetes-infrastructure.git
        targetRevision: HEAD
        path: "{{ path }}"
        helm:
          releaseName: "{{ path.basenameNormalized }} }}"
          valueFiles:
            - "values.{{ values.environment }}.yaml"
      destination:
        name: "{{ name }}"
        namespace: infrastructure-{{ path.basenameNormalized }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
