apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
spec:
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: https://github.com/bcrisp4/kubernetes-infrastructure.git
              revision: HEAD
              directories:
                - path: "{{ name }}/*/*"
  template:
    metadata:
      name: "{{ path.basenameNormalized }}.infra-{{ path[1] }}.{{ nameNormalized }}"
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/bcrisp4/kubernetes-infrastructure.git
        targetRevision: HEAD
        path: "{{ path }}"
        helm:
          releaseName: "{{ path.basenameNormalized }}"
          valueFiles:
            - "values.yaml"
      destination:
        name: "{{ name }}"
        namespace: infra-{{ path[1] }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
