{{- if not .Values.bootstrap }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster addons
  sourceRepos:
  - "https://github.com/bcrisp4/kubernetes-config.git"
  destinations:
  - namespace: "*"
    name: {{ .Values.cluster.name }}
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
{{- end }}