cluster:
  name: do-nyc1-1

argo-cd:
  configs:
    cm:
      accounts.ben: apiKey,login
      accounts.ben.enabled: "true"
      admin.enabled: "true"
      applicationsetcontroller.enable.new.git.file.globbing: "true"
      resource.customizations.ignoreDifferences.all: |
        jqPathExpressions:
        - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
        - .spec.template.spec.initContainers[].env[].valueFrom.resourceFieldRef.divisor
      resource.exclusions: |
        - apiGroups:
          - "*"
          kinds:
          - "Endpoints"
          - "ControllerRevision"
          - "CiliumEndpoint"
          - "CiliumIdentity"
          - "EndpointSlice"
          clusters:
          - "*"

  controller:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 1000M
      limits:
        memory: 1000M

  dex:
    enabled: false

  redis:
    resources:
      requests:
        cpu: 50m
        memory: 250Mi
      limits:
        memory: 250Mi

  server:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 250M
      limits:
        memory: 250M
    ingress:
      enabled: true
      ingressClassName: tailscale
      hostname: argocd
      extraTls:
        - hosts:
            - argocd
          secretName: argocd-tls

  repoServer:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 500M
      limits:
        memory: 500M

  applicationSet:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 100M
      limits:
        memory: 100M

  notifications:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 100M
      limits:
        memory: 100M
